DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS categories;

CREATE TABLE articles (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    title   STRING NOT NULL,
    body    STRING NOT NULL,
    slug    STRING NOT NULL,
    cat     STRING NOT NULL
);

CREATE TABLE categories (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    name    STRING NOT NULL
);
